// Code generated by MockGen. DO NOT EDIT.
// Source: usecases_interface.go
//
// Generated by this command:
//
//	mockgen -source=usecases_interface.go -destination=../mocks/mock_usecases.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "MydroX/anicetus/internal/identity/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdentityUsecases is a mock of IdentityUsecases interface.
type MockIdentityUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityUsecasesMockRecorder
	isgomock struct{}
}

// MockIdentityUsecasesMockRecorder is the mock recorder for MockIdentityUsecases.
type MockIdentityUsecasesMockRecorder struct {
	mock *MockIdentityUsecases
}

// NewMockIdentityUsecases creates a new mock instance.
func NewMockIdentityUsecases(ctrl *gomock.Controller) *MockIdentityUsecases {
	mock := &MockIdentityUsecases{ctrl: ctrl}
	mock.recorder = &MockIdentityUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityUsecases) EXPECT() *MockIdentityUsecasesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityUsecases) Create(ctx context.Context, user *dto.CreateUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIdentityUsecasesMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityUsecases)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockIdentityUsecases) Delete(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityUsecasesMockRecorder) Delete(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityUsecases)(nil).Delete), ctx, uuid)
}

// Get mocks base method.
func (m *MockIdentityUsecases) Get(ctx context.Context, uuid string) (*dto.GetUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*dto.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIdentityUsecasesMockRecorder) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdentityUsecases)(nil).Get), ctx, uuid)
}

// GetAllUsers mocks base method.
func (m *MockIdentityUsecases) GetAllUsers(ctx context.Context) (*dto.GetAllUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx)
	ret0, _ := ret[0].(*dto.GetAllUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockIdentityUsecasesMockRecorder) GetAllUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockIdentityUsecases)(nil).GetAllUsers), ctx)
}

// Update mocks base method.
func (m *MockIdentityUsecases) Update(ctx context.Context, user *dto.UpdateUserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIdentityUsecasesMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityUsecases)(nil).Update), ctx, user)
}

// UpdateEmail mocks base method.
func (m *MockIdentityUsecases) UpdateEmail(ctx context.Context, uuid, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", ctx, uuid, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockIdentityUsecasesMockRecorder) UpdateEmail(ctx, uuid, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockIdentityUsecases)(nil).UpdateEmail), ctx, uuid, email)
}

// UpdatePassword mocks base method.
func (m *MockIdentityUsecases) UpdatePassword(ctx context.Context, uuid, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, uuid, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockIdentityUsecasesMockRecorder) UpdatePassword(ctx, uuid, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIdentityUsecases)(nil).UpdatePassword), ctx, uuid, password)
}
