variables:
  GOLANG_VERSION: '1.24.1-alpine3.21'
  GOLANGCI_LINT_VERSION: 'v2.0.1-alpine'

image: golang:$GOLANG_VERSION

stages:
  - test
  - build
  # - deploy

lint:
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION
  stage: test
  script:
    - golangci-lint run 

go-test:
    stage: test
    script:
      - go test -v -coverpkg=./... -coverprofile=profile.cov ./...
      - go tool cover -func profile.cov
    coverage: '/\(statements\)(?:\s+)?(\d+(?:\.\d+)?%)/'
        
build:
  stage: build
  script:
    - go build -o app cmd/main.go
