image: golang:1.22.4

stages:
  - test
  - build
  # - deploy

lint:
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION
  stage: test
  script:
    - golangci-lint run --print-issued-lines=false

go-test:
    stage: test
    services:
      - postgres
    script:
      - go test -v -coverpkg=./... -coverprofile=profile.cov ./...
      - go tool cover -func profile.cov
    coverage: '/\(statements\)(?:\s+)?(\d+(?:\.\d+)?%)/'
        
build:
  stage: build
  script:
    - go build -o gateway cmd/gateway/main.go

variables:
  GOLANGCI_LINT_VERSION: 'v1.62.2-alpine'
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432