# https://golangci-lint.run/usage/configuration/#config-file
version: "2"

linters:
  enable:
    - decorder
    - dupl
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - predeclared
    - reassign
    - recvcheck
    - revive
    - staticcheck
    - tagalign
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
  exclusions:
    generated: lax # Do not lint generated files.
    paths:
      - _test\.go # Do not lint test files.

  settings:
    revive:
      enable-all-rules: true
      severity: error # We want it to be blocking from now on.
      rules:
        - name: add-constant
          disabled: true
          arguments:
            # Do not force to use constants for zero values.
            - allow-floats: "0.0,0."
              allow-ints: "0"
              allow-strs: '""'
        - name: cyclomatic
          arguments:
            - 10 # Default value (4) is too low.
        - name: enforce-map-style
          arguments:
            - literal # Use `a := map[X]Y{}` (instead of `a := make(map[X]Y, ...)`).
        - name: enforce-slice-style
          arguments:
            - literal # Use `a := []X{}` (instead of `a := make([]X, ...)`).
        - name: line-length-limit
          arguments:
            - 120 # Match `golines` settings.
        - name: use-errors-new
          disabled: true # Always use `fmt.Errorf`.
        - name: exported
          disabled: true # Need to add documentation to all exported functions, interface, types and so on...
        - name: line-length-limit
          arguments:
            - 150 # Change the default value 120 to 150 for maximum line length.
        - name: package-comments
          disabled: true # Do not force to write package comments.
        - name: receiver-naming
          disabled: true # Do not force to use any specific receiver name.
        - name: cognitive-complexity
          arguments:
            - 12 # Default value (7) is too low.
        - name: max-public-structs
          arguments:
            - 8 # Default value (5) is too low.
        - name: get-return
          disabled: true # Do not force to use `Get` prefix for getters.
    staticcheck:
      checks:
        # Do not force to write `foo.Baz` if the developer explicitely want to write `foo.Bar.Baz` where `Bar` is an
        # embedded field (reference: https://staticcheck.dev/docs/checks/#QF1008)
        - -QF1008

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

  exclusions:
    generated: lax # Do not format generated files.

  settings:
    golines:
      max-len: 150
      shorten-comments: true # Apply the same rule for comments.

issues:
  fix: true # Automatically fix issues if possible.
