FROM node:22.14.0-alpine3.21

RUN npm install -g pnpm@10.5.2

WORKDIR /app

COPY web/package.json web/pnpm-lock.yaml ./

RUN pnpm install

COPY ./web .

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]