// Code generated by MockGen. DO NOT EDIT.
// Source: jwt.go
//
// Generated by this command:
//
//	mockgen -source=jwt.go -destination=mock_jwt.go -package=jwt
//

// Package jwt is a generated GoMock package.
package jwt

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// CreateAccessToken mocks base method.
func (m *MockTokenService) CreateAccessToken(userUUID string, permissions, audiences []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessToken", userUUID, permissions, audiences)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessToken indicates an expected call of CreateAccessToken.
func (mr *MockTokenServiceMockRecorder) CreateAccessToken(userUUID, permissions, audiences any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessToken", reflect.TypeOf((*MockTokenService)(nil).CreateAccessToken), userUUID, permissions, audiences)
}

// CreateRefreshToken mocks base method.
func (m *MockTokenService) CreateRefreshToken(userUUID, sessionUUID string, audiences []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", userUUID, sessionUUID, audiences)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockTokenServiceMockRecorder) CreateRefreshToken(userUUID, sessionUUID, audiences any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockTokenService)(nil).CreateRefreshToken), userUUID, sessionUUID, audiences)
}

// ParseAccessToken mocks base method.
func (m *MockTokenService) ParseAccessToken(tokenString string) (*AccessClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessToken", tokenString)
	ret0, _ := ret[0].(*AccessClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessToken indicates an expected call of ParseAccessToken.
func (mr *MockTokenServiceMockRecorder) ParseAccessToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessToken", reflect.TypeOf((*MockTokenService)(nil).ParseAccessToken), tokenString)
}

// ParseRefreshToken mocks base method.
func (m *MockTokenService) ParseRefreshToken(tokenString string) (*RefreshClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefreshToken", tokenString)
	ret0, _ := ret[0].(*RefreshClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRefreshToken indicates an expected call of ParseRefreshToken.
func (mr *MockTokenServiceMockRecorder) ParseRefreshToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefreshToken", reflect.TypeOf((*MockTokenService)(nil).ParseRefreshToken), tokenString)
}

// ParseToken mocks base method.
func (m *MockTokenService) ParseToken(tokenString string) (*BaseClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", tokenString)
	ret0, _ := ret[0].(*BaseClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockTokenServiceMockRecorder) ParseToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockTokenService)(nil).ParseToken), tokenString)
}

// MockAudienceProvider is a mock of AudienceProvider interface.
type MockAudienceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAudienceProviderMockRecorder
	isgomock struct{}
}

// MockAudienceProviderMockRecorder is the mock recorder for MockAudienceProvider.
type MockAudienceProviderMockRecorder struct {
	mock *MockAudienceProvider
}

// NewMockAudienceProvider creates a new mock instance.
func NewMockAudienceProvider(ctrl *gomock.Controller) *MockAudienceProvider {
	mock := &MockAudienceProvider{ctrl: ctrl}
	mock.recorder = &MockAudienceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudienceProvider) EXPECT() *MockAudienceProviderMockRecorder {
	return m.recorder
}

// GetAllowedAudiences mocks base method.
func (m *MockAudienceProvider) GetAllowedAudiences(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedAudiences", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowedAudiences indicates an expected call of GetAllowedAudiences.
func (mr *MockAudienceProviderMockRecorder) GetAllowedAudiences(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedAudiences", reflect.TypeOf((*MockAudienceProvider)(nil).GetAllowedAudiences), ctx)
}

// GetUserAudiences mocks base method.
func (m *MockAudienceProvider) GetUserAudiences(ctx context.Context, userUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAudiences", ctx, userUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAudiences indicates an expected call of GetUserAudiences.
func (mr *MockAudienceProviderMockRecorder) GetUserAudiences(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAudiences", reflect.TypeOf((*MockAudienceProvider)(nil).GetUserAudiences), ctx, userUUID)
}
