// Code generated by MockGen. DO NOT EDIT.
// Source: repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=repository_interface.go -destination=../mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "MydroX/anicetus/internal/authentication/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// DeleteAllUserSessions mocks base method.
func (m *MockSessionStore) DeleteAllUserSessions(ctx context.Context, userUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllUserSessions", ctx, userUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllUserSessions indicates an expected call of DeleteAllUserSessions.
func (mr *MockSessionStoreMockRecorder) DeleteAllUserSessions(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllUserSessions", reflect.TypeOf((*MockSessionStore)(nil).DeleteAllUserSessions), ctx, userUUID)
}

// DeleteSession mocks base method.
func (m *MockSessionStore) DeleteSession(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionStoreMockRecorder) DeleteSession(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionStore)(nil).DeleteSession), ctx, uuid)
}

// GetSessionByUUID mocks base method.
func (m *MockSessionStore) GetSessionByUUID(ctx context.Context, uuid string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByUUID", ctx, uuid)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByUUID indicates an expected call of GetSessionByUUID.
func (mr *MockSessionStoreMockRecorder) GetSessionByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByUUID", reflect.TypeOf((*MockSessionStore)(nil).GetSessionByUUID), ctx, uuid)
}

// SaveSession mocks base method.
func (m *MockSessionStore) SaveSession(ctx context.Context, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockSessionStoreMockRecorder) SaveSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockSessionStore)(nil).SaveSession), ctx, session)
}

// UpdateSessionLastUsed mocks base method.
func (m *MockSessionStore) UpdateSessionLastUsed(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionLastUsed", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionLastUsed indicates an expected call of UpdateSessionLastUsed.
func (mr *MockSessionStoreMockRecorder) UpdateSessionLastUsed(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionLastUsed", reflect.TypeOf((*MockSessionStore)(nil).UpdateSessionLastUsed), ctx, uuid)
}
