// Code generated by MockGen. DO NOT EDIT.
// Source: usecases_interface.go
//
// Generated by this command:
//
//	mockgen -source=usecases_interface.go -destination=../mocks/mock_usecases.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "MydroX/anicetus/internal/authentication/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticationUsecases is a mock of AuthenticationUsecases interface.
type MockAuthenticationUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationUsecasesMockRecorder
	isgomock struct{}
}

// MockAuthenticationUsecasesMockRecorder is the mock recorder for MockAuthenticationUsecases.
type MockAuthenticationUsecasesMockRecorder struct {
	mock *MockAuthenticationUsecases
}

// NewMockAuthenticationUsecases creates a new mock instance.
func NewMockAuthenticationUsecases(ctrl *gomock.Controller) *MockAuthenticationUsecases {
	mock := &MockAuthenticationUsecases{ctrl: ctrl}
	mock.recorder = &MockAuthenticationUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationUsecases) EXPECT() *MockAuthenticationUsecasesMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthenticationUsecases) Login(ctx context.Context, req *dto.LoginRequest) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockAuthenticationUsecasesMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthenticationUsecases)(nil).Login), ctx, req)
}

// Logout mocks base method.
func (m *MockAuthenticationUsecases) Logout(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthenticationUsecasesMockRecorder) Logout(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthenticationUsecases)(nil).Logout), ctx, refreshToken)
}

// RefreshToken mocks base method.
func (m *MockAuthenticationUsecases) RefreshToken(ctx context.Context, refreshToken string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthenticationUsecasesMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthenticationUsecases)(nil).RefreshToken), ctx, refreshToken)
}
