services:
  app:
    container_name: app
    build:
      context: ..
    volumes: 
      - ../.:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - project-v
  db:
    container_name: db
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - project-v

  # TODO: Fix hot reload for dashboard
  # dashboard:
  #   container_name: dashboard
  #   build:
  #     context: ..
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - project-v

volumes:
  postgres:

networks:
  project-v:
    external: true