//revive:disable:cognitive-complexity
package uuid

import (
	"strings"
	"testing"

	"github.com/google/uuid"
)

func TestNewWithPrefix(t *testing.T) {
	tests := []struct {
		name   string
		prefix string
	}{
		{
			name:   "with refresh prefix",
			prefix: "refresh",
		},
		{
			name:   "with access prefix",
			prefix: "access",
		},
		{
			name:   "with empty prefix",
			prefix: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			token := NewWithPrefix(tt.prefix)

			// Check that the result is not empty
			if token == "" {
				t.Error("expected non-empty token, got empty string")
			}

			// Check that the prefix is correctly applied
			if !strings.HasPrefix(token, tt.prefix+"_") {
				t.Errorf("expected token to start with %s_, got %s", tt.prefix, token)
			}

			// Split the token and validate UUID format
			parts := strings.Split(token, "_")
			if len(parts) != 2 {
				t.Errorf("expected token to have format prefix_uuid, got %s", token)
				return
			}

			// Parse the UUID part
			_, err := uuid.Parse(parts[1])
			if err != nil {
				t.Errorf("expected valid UUID in token, got error: %v", err)
			}
		})
	}
}

func TestValidateWithPrefix(t *testing.T) {
	validUUID := uuid.New().String()

	tests := []struct {
		name        string
		token       string
		expectValid bool
		expectError string
	}{
		{
			name:        "valid token",
			token:       "refresh_" + validUUID,
			expectValid: true,
			expectError: "",
		},
		{
			name:        "empty token",
			token:       "",
			expectValid: false,
			expectError: "token is empty",
		},
		{
			name:        "missing underscore",
			token:       "refresh" + validUUID,
			expectValid: false,
			expectError: "invalid token format",
		},
		{
			name:        "too many underscores",
			token:       "refresh_extra_" + validUUID,
			expectValid: false,
			expectError: "invalid token format",
		},
		{
			name:        "invalid UUID",
			token:       "refresh_not-a-valid-uuid",
			expectValid: false,
			expectError: "invalid UUID format",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			valid, err := ValidateWithPrefix(tt.token)

			// Check validity result
			if valid != tt.expectValid {
				t.Errorf("expected valid=%v, got %v", tt.expectValid, valid)
			}

			// Check error result
			if tt.expectError == "" {
				if err != nil {
					t.Errorf("expected no error, got %v", err)
				}
			} else {
				if err == nil {
					t.Errorf("expected error containing '%s', got nil", tt.expectError)
				} else if !strings.Contains(err.Error(), tt.expectError) {
					t.Errorf("expected error containing '%s', got '%s'", tt.expectError, err.Error())
				}
			}
		})
	}
}

func TestEndToEnd(t *testing.T) {
	// Test that tokens generated by NewWithPrefix pass validation
	prefixes := []string{"refresh", "access", "verify", ""}

	for _, prefix := range prefixes {
		t.Run("prefix_"+prefix, func(t *testing.T) {
			// Generate token
			token := NewWithPrefix(prefix)

			// Validate token
			valid, err := ValidateWithPrefix(token)

			// Check results
			if !valid {
				t.Errorf("token generated with NewWithPrefix failed validation: %v", err)
			}
			if err != nil {
				t.Errorf("unexpected error: %v", err)
			}
		})
	}
}
