// Code generated by MockGen. DO NOT EDIT.
// Source: repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=repository_interface.go -destination=../mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "MydroX/anicetus/internal/authorization/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizationRepository is a mock of AuthorizationRepository interface.
type MockAuthorizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthorizationRepositoryMockRecorder is the mock recorder for MockAuthorizationRepository.
type MockAuthorizationRepositoryMockRecorder struct {
	mock *MockAuthorizationRepository
}

// NewMockAuthorizationRepository creates a new mock instance.
func NewMockAuthorizationRepository(ctrl *gomock.Controller) *MockAuthorizationRepository {
	mock := &MockAuthorizationRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationRepository) EXPECT() *MockAuthorizationRepositoryMockRecorder {
	return m.recorder
}

// AssignPermissionToRole mocks base method.
func (m *MockAuthorizationRepository) AssignPermissionToRole(ctx context.Context, roleUUID, permissionUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPermissionToRole", ctx, roleUUID, permissionUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignPermissionToRole indicates an expected call of AssignPermissionToRole.
func (mr *MockAuthorizationRepositoryMockRecorder) AssignPermissionToRole(ctx, roleUUID, permissionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPermissionToRole", reflect.TypeOf((*MockAuthorizationRepository)(nil).AssignPermissionToRole), ctx, roleUUID, permissionUUID)
}

// AssignRoleToUser mocks base method.
func (m *MockAuthorizationRepository) AssignRoleToUser(ctx context.Context, userUUID, roleUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToUser", ctx, userUUID, roleUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleToUser indicates an expected call of AssignRoleToUser.
func (mr *MockAuthorizationRepositoryMockRecorder) AssignRoleToUser(ctx, userUUID, roleUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToUser", reflect.TypeOf((*MockAuthorizationRepository)(nil).AssignRoleToUser), ctx, userUUID, roleUUID)
}

// CreatePermission mocks base method.
func (m *MockAuthorizationRepository) CreatePermission(ctx context.Context, perm *models.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", ctx, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockAuthorizationRepositoryMockRecorder) CreatePermission(ctx, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockAuthorizationRepository)(nil).CreatePermission), ctx, perm)
}

// CreateRole mocks base method.
func (m *MockAuthorizationRepository) CreateRole(ctx context.Context, role *models.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockAuthorizationRepositoryMockRecorder) CreateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockAuthorizationRepository)(nil).CreateRole), ctx, role)
}

// DeletePermission mocks base method.
func (m *MockAuthorizationRepository) DeletePermission(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermission", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermission indicates an expected call of DeletePermission.
func (mr *MockAuthorizationRepositoryMockRecorder) DeletePermission(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermission", reflect.TypeOf((*MockAuthorizationRepository)(nil).DeletePermission), ctx, uuid)
}

// DeleteRole mocks base method.
func (m *MockAuthorizationRepository) DeleteRole(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockAuthorizationRepositoryMockRecorder) DeleteRole(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockAuthorizationRepository)(nil).DeleteRole), ctx, uuid)
}

// GetAllPermissions mocks base method.
func (m *MockAuthorizationRepository) GetAllPermissions(ctx context.Context) ([]*models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPermissions", ctx)
	ret0, _ := ret[0].([]*models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPermissions indicates an expected call of GetAllPermissions.
func (mr *MockAuthorizationRepositoryMockRecorder) GetAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPermissions", reflect.TypeOf((*MockAuthorizationRepository)(nil).GetAllPermissions), ctx)
}

// GetAllRoles mocks base method.
func (m *MockAuthorizationRepository) GetAllRoles(ctx context.Context) ([]*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRoles", ctx)
	ret0, _ := ret[0].([]*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRoles indicates an expected call of GetAllRoles.
func (mr *MockAuthorizationRepositoryMockRecorder) GetAllRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRoles", reflect.TypeOf((*MockAuthorizationRepository)(nil).GetAllRoles), ctx)
}

// GetRoleByName mocks base method.
func (m *MockAuthorizationRepository) GetRoleByName(ctx context.Context, name string) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", ctx, name)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockAuthorizationRepositoryMockRecorder) GetRoleByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockAuthorizationRepository)(nil).GetRoleByName), ctx, name)
}

// GetRoleByUUID mocks base method.
func (m *MockAuthorizationRepository) GetRoleByUUID(ctx context.Context, uuid string) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByUUID", ctx, uuid)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByUUID indicates an expected call of GetRoleByUUID.
func (mr *MockAuthorizationRepositoryMockRecorder) GetRoleByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByUUID", reflect.TypeOf((*MockAuthorizationRepository)(nil).GetRoleByUUID), ctx, uuid)
}

// GetRolePermissions mocks base method.
func (m *MockAuthorizationRepository) GetRolePermissions(ctx context.Context, roleUUID string) ([]*models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", ctx, roleUUID)
	ret0, _ := ret[0].([]*models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockAuthorizationRepositoryMockRecorder) GetRolePermissions(ctx, roleUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockAuthorizationRepository)(nil).GetRolePermissions), ctx, roleUUID)
}

// GetUserPermissions mocks base method.
func (m *MockAuthorizationRepository) GetUserPermissions(ctx context.Context, userUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", ctx, userUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockAuthorizationRepositoryMockRecorder) GetUserPermissions(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockAuthorizationRepository)(nil).GetUserPermissions), ctx, userUUID)
}

// GetUserRoles mocks base method.
func (m *MockAuthorizationRepository) GetUserRoles(ctx context.Context, userUUID string) ([]*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, userUUID)
	ret0, _ := ret[0].([]*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockAuthorizationRepositoryMockRecorder) GetUserRoles(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockAuthorizationRepository)(nil).GetUserRoles), ctx, userUUID)
}

// RemovePermissionFromRole mocks base method.
func (m *MockAuthorizationRepository) RemovePermissionFromRole(ctx context.Context, roleUUID, permissionUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePermissionFromRole", ctx, roleUUID, permissionUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePermissionFromRole indicates an expected call of RemovePermissionFromRole.
func (mr *MockAuthorizationRepositoryMockRecorder) RemovePermissionFromRole(ctx, roleUUID, permissionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePermissionFromRole", reflect.TypeOf((*MockAuthorizationRepository)(nil).RemovePermissionFromRole), ctx, roleUUID, permissionUUID)
}

// RemoveRoleFromUser mocks base method.
func (m *MockAuthorizationRepository) RemoveRoleFromUser(ctx context.Context, userUUID, roleUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoleFromUser", ctx, userUUID, roleUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoleFromUser indicates an expected call of RemoveRoleFromUser.
func (mr *MockAuthorizationRepositoryMockRecorder) RemoveRoleFromUser(ctx, userUUID, roleUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoleFromUser", reflect.TypeOf((*MockAuthorizationRepository)(nil).RemoveRoleFromUser), ctx, userUUID, roleUUID)
}

// UpdateRole mocks base method.
func (m *MockAuthorizationRepository) UpdateRole(ctx context.Context, role *models.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockAuthorizationRepositoryMockRecorder) UpdateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockAuthorizationRepository)(nil).UpdateRole), ctx, role)
}
