// Code generated by MockGen. DO NOT EDIT.
// Source: usecases_interface.go
//
// Generated by this command:
//
//	mockgen -source=usecases_interface.go -destination=../mocks/mock_usecases.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "MydroX/anicetus/internal/authorization/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizationUsecases is a mock of AuthorizationUsecases interface.
type MockAuthorizationUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationUsecasesMockRecorder
	isgomock struct{}
}

// MockAuthorizationUsecasesMockRecorder is the mock recorder for MockAuthorizationUsecases.
type MockAuthorizationUsecasesMockRecorder struct {
	mock *MockAuthorizationUsecases
}

// NewMockAuthorizationUsecases creates a new mock instance.
func NewMockAuthorizationUsecases(ctrl *gomock.Controller) *MockAuthorizationUsecases {
	mock := &MockAuthorizationUsecases{ctrl: ctrl}
	mock.recorder = &MockAuthorizationUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationUsecases) EXPECT() *MockAuthorizationUsecasesMockRecorder {
	return m.recorder
}

// AssignPermissionToRole mocks base method.
func (m *MockAuthorizationUsecases) AssignPermissionToRole(ctx context.Context, roleUUID, permissionUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPermissionToRole", ctx, roleUUID, permissionUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignPermissionToRole indicates an expected call of AssignPermissionToRole.
func (mr *MockAuthorizationUsecasesMockRecorder) AssignPermissionToRole(ctx, roleUUID, permissionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPermissionToRole", reflect.TypeOf((*MockAuthorizationUsecases)(nil).AssignPermissionToRole), ctx, roleUUID, permissionUUID)
}

// AssignRoleToUser mocks base method.
func (m *MockAuthorizationUsecases) AssignRoleToUser(ctx context.Context, userUUID, roleUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToUser", ctx, userUUID, roleUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleToUser indicates an expected call of AssignRoleToUser.
func (mr *MockAuthorizationUsecasesMockRecorder) AssignRoleToUser(ctx, userUUID, roleUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToUser", reflect.TypeOf((*MockAuthorizationUsecases)(nil).AssignRoleToUser), ctx, userUUID, roleUUID)
}

// CreatePermission mocks base method.
func (m *MockAuthorizationUsecases) CreatePermission(ctx context.Context, req *dto.CreatePermissionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockAuthorizationUsecasesMockRecorder) CreatePermission(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockAuthorizationUsecases)(nil).CreatePermission), ctx, req)
}

// CreateRole mocks base method.
func (m *MockAuthorizationUsecases) CreateRole(ctx context.Context, req *dto.CreateRoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockAuthorizationUsecasesMockRecorder) CreateRole(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockAuthorizationUsecases)(nil).CreateRole), ctx, req)
}

// DeleteRole mocks base method.
func (m *MockAuthorizationUsecases) DeleteRole(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockAuthorizationUsecasesMockRecorder) DeleteRole(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockAuthorizationUsecases)(nil).DeleteRole), ctx, uuid)
}

// GetAllPermissions mocks base method.
func (m *MockAuthorizationUsecases) GetAllPermissions(ctx context.Context) ([]*dto.PermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPermissions", ctx)
	ret0, _ := ret[0].([]*dto.PermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPermissions indicates an expected call of GetAllPermissions.
func (mr *MockAuthorizationUsecasesMockRecorder) GetAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPermissions", reflect.TypeOf((*MockAuthorizationUsecases)(nil).GetAllPermissions), ctx)
}

// GetAllRoles mocks base method.
func (m *MockAuthorizationUsecases) GetAllRoles(ctx context.Context) ([]*dto.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRoles", ctx)
	ret0, _ := ret[0].([]*dto.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRoles indicates an expected call of GetAllRoles.
func (mr *MockAuthorizationUsecasesMockRecorder) GetAllRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRoles", reflect.TypeOf((*MockAuthorizationUsecases)(nil).GetAllRoles), ctx)
}

// GetUserPermissions mocks base method.
func (m *MockAuthorizationUsecases) GetUserPermissions(ctx context.Context, userUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", ctx, userUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockAuthorizationUsecasesMockRecorder) GetUserPermissions(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockAuthorizationUsecases)(nil).GetUserPermissions), ctx, userUUID)
}

// GetUserRoles mocks base method.
func (m *MockAuthorizationUsecases) GetUserRoles(ctx context.Context, userUUID string) ([]*dto.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, userUUID)
	ret0, _ := ret[0].([]*dto.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockAuthorizationUsecasesMockRecorder) GetUserRoles(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockAuthorizationUsecases)(nil).GetUserRoles), ctx, userUUID)
}

// RemovePermissionFromRole mocks base method.
func (m *MockAuthorizationUsecases) RemovePermissionFromRole(ctx context.Context, roleUUID, permissionUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePermissionFromRole", ctx, roleUUID, permissionUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePermissionFromRole indicates an expected call of RemovePermissionFromRole.
func (mr *MockAuthorizationUsecasesMockRecorder) RemovePermissionFromRole(ctx, roleUUID, permissionUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePermissionFromRole", reflect.TypeOf((*MockAuthorizationUsecases)(nil).RemovePermissionFromRole), ctx, roleUUID, permissionUUID)
}

// RemoveRoleFromUser mocks base method.
func (m *MockAuthorizationUsecases) RemoveRoleFromUser(ctx context.Context, userUUID, roleUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoleFromUser", ctx, userUUID, roleUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoleFromUser indicates an expected call of RemoveRoleFromUser.
func (mr *MockAuthorizationUsecasesMockRecorder) RemoveRoleFromUser(ctx, userUUID, roleUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoleFromUser", reflect.TypeOf((*MockAuthorizationUsecases)(nil).RemoveRoleFromUser), ctx, userUUID, roleUUID)
}

// UpdateRole mocks base method.
func (m *MockAuthorizationUsecases) UpdateRole(ctx context.Context, uuid string, req *dto.UpdateRoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, uuid, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockAuthorizationUsecasesMockRecorder) UpdateRole(ctx, uuid, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockAuthorizationUsecases)(nil).UpdateRole), ctx, uuid, req)
}
