// Code generated by MockGen. DO NOT EDIT.
// Source: usecases_interface.go
//
// Generated by this command:
//
//	mockgen -source=usecases_interface.go -destination=../mocks/mock_usescases.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "MydroX/anicetus/internal/common/context"
	dto "MydroX/anicetus/internal/iam/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIamUsecasesInterface is a mock of IamUsecasesInterface interface.
type MockIamUsecasesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIamUsecasesInterfaceMockRecorder
	isgomock struct{}
}

// MockIamUsecasesInterfaceMockRecorder is the mock recorder for MockIamUsecasesInterface.
type MockIamUsecasesInterfaceMockRecorder struct {
	mock *MockIamUsecasesInterface
}

// NewMockIamUsecasesInterface creates a new mock instance.
func NewMockIamUsecasesInterface(ctrl *gomock.Controller) *MockIamUsecasesInterface {
	mock := &MockIamUsecasesInterface{ctrl: ctrl}
	mock.recorder = &MockIamUsecasesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIamUsecasesInterface) EXPECT() *MockIamUsecasesInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockIamUsecasesInterface) Login(ctx *context.AppContext, req *dto.LoginRequest) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockIamUsecasesInterfaceMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIamUsecasesInterface)(nil).Login), ctx, req)
}

// Logout mocks base method.
func (m *MockIamUsecasesInterface) Logout(ctx *context.AppContext, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockIamUsecasesInterfaceMockRecorder) Logout(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockIamUsecasesInterface)(nil).Logout), ctx, token)
}

// RefreshToken mocks base method.
func (m *MockIamUsecasesInterface) RefreshToken(ctx *context.AppContext, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIamUsecasesInterfaceMockRecorder) RefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIamUsecasesInterface)(nil).RefreshToken), ctx, token)
}
