// Code generated by MockGen. DO NOT EDIT.
// Source: repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=repository_interface.go -destination=../mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "MydroX/anicetus/internal/common/context"
	models "MydroX/anicetus/internal/iam/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIamRepository is a mock of IamRepository interface.
type MockIamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIamRepositoryMockRecorder
	isgomock struct{}
}

// MockIamRepositoryMockRecorder is the mock recorder for MockIamRepository.
type MockIamRepositoryMockRecorder struct {
	mock *MockIamRepository
}

// NewMockIamRepository creates a new mock instance.
func NewMockIamRepository(ctrl *gomock.Controller) *MockIamRepository {
	mock := &MockIamRepository{ctrl: ctrl}
	mock.recorder = &MockIamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIamRepository) EXPECT() *MockIamRepositoryMockRecorder {
	return m.recorder
}

// SaveSession mocks base method.
func (m *MockIamRepository) SaveSession(ctx *context.AppContext, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockIamRepositoryMockRecorder) SaveSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockIamRepository)(nil).SaveSession), ctx, session)
}
