// Code generated by MockGen. DO NOT EDIT.
// Source: repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=repository_interface.go -destination=../mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "MydroX/anicetus/internal/common/context"
	models "MydroX/anicetus/internal/iam/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIamRepository is a mock of IamRepository interface.
type MockIamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIamRepositoryMockRecorder
	isgomock struct{}
}

// MockIamRepositoryMockRecorder is the mock recorder for MockIamRepository.
type MockIamRepositoryMockRecorder struct {
	mock *MockIamRepository
}

// NewMockIamRepository creates a new mock instance.
func NewMockIamRepository(ctrl *gomock.Controller) *MockIamRepository {
	mock := &MockIamRepository{ctrl: ctrl}
	mock.recorder = &MockIamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIamRepository) EXPECT() *MockIamRepositoryMockRecorder {
	return m.recorder
}

// SaveSession mocks base method.
func (m *MockIamRepository) SaveSession(ctx *context.AppContext, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockIamRepositoryMockRecorder) SaveSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockIamRepository)(nil).SaveSession), ctx, session)
}

// MockAudienceStore is a mock of AudienceStore interface.
type MockAudienceStore struct {
	ctrl     *gomock.Controller
	recorder *MockAudienceStoreMockRecorder
	isgomock struct{}
}

// MockAudienceStoreMockRecorder is the mock recorder for MockAudienceStore.
type MockAudienceStoreMockRecorder struct {
	mock *MockAudienceStore
}

// NewMockAudienceStore creates a new mock instance.
func NewMockAudienceStore(ctrl *gomock.Controller) *MockAudienceStore {
	mock := &MockAudienceStore{ctrl: ctrl}
	mock.recorder = &MockAudienceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudienceStore) EXPECT() *MockAudienceStoreMockRecorder {
	return m.recorder
}

// GetAllowedAudiences mocks base method.
func (m *MockAudienceStore) GetAllowedAudiences() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedAudiences")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowedAudiences indicates an expected call of GetAllowedAudiences.
func (mr *MockAudienceStoreMockRecorder) GetAllowedAudiences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedAudiences", reflect.TypeOf((*MockAudienceStore)(nil).GetAllowedAudiences))
}

// IsValidAudience mocks base method.
func (m *MockAudienceStore) IsValidAudience(audience string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidAudience", audience)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidAudience indicates an expected call of IsValidAudience.
func (mr *MockAudienceStoreMockRecorder) IsValidAudience(audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidAudience", reflect.TypeOf((*MockAudienceStore)(nil).IsValidAudience), audience)
}

// RegisterAudience mocks base method.
func (m *MockAudienceStore) RegisterAudience(audience string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAudience", audience, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAudience indicates an expected call of RegisterAudience.
func (mr *MockAudienceStoreMockRecorder) RegisterAudience(audience, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAudience", reflect.TypeOf((*MockAudienceStore)(nil).RegisterAudience), audience, metadata)
}

// RevokeAudience mocks base method.
func (m *MockAudienceStore) RevokeAudience(audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAudience", audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAudience indicates an expected call of RevokeAudience.
func (mr *MockAudienceStoreMockRecorder) RevokeAudience(audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAudience", reflect.TypeOf((*MockAudienceStore)(nil).RevokeAudience), audience)
}
