// Code generated by MockGen. DO NOT EDIT.
// Source: repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=repository_interface.go -destination=../mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "MydroX/anicetus/internal/common/context"
	models "MydroX/anicetus/internal/iam/models"
	context0 "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIamStore is a mock of IamStore interface.
type MockIamStore struct {
	ctrl     *gomock.Controller
	recorder *MockIamStoreMockRecorder
	isgomock struct{}
}

// MockIamStoreMockRecorder is the mock recorder for MockIamStore.
type MockIamStoreMockRecorder struct {
	mock *MockIamStore
}

// NewMockIamStore creates a new mock instance.
func NewMockIamStore(ctrl *gomock.Controller) *MockIamStore {
	mock := &MockIamStore{ctrl: ctrl}
	mock.recorder = &MockIamStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIamStore) EXPECT() *MockIamStoreMockRecorder {
	return m.recorder
}

// SaveSession mocks base method.
func (m *MockIamStore) SaveSession(ctx *context.AppContext, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockIamStoreMockRecorder) SaveSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockIamStore)(nil).SaveSession), ctx, session)
}

// MockAudienceStore is a mock of AudienceStore interface.
type MockAudienceStore struct {
	ctrl     *gomock.Controller
	recorder *MockAudienceStoreMockRecorder
	isgomock struct{}
}

// MockAudienceStoreMockRecorder is the mock recorder for MockAudienceStore.
type MockAudienceStoreMockRecorder struct {
	mock *MockAudienceStore
}

// NewMockAudienceStore creates a new mock instance.
func NewMockAudienceStore(ctrl *gomock.Controller) *MockAudienceStore {
	mock := &MockAudienceStore{ctrl: ctrl}
	mock.recorder = &MockAudienceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudienceStore) EXPECT() *MockAudienceStoreMockRecorder {
	return m.recorder
}

// AssignAudienceToUser mocks base method.
func (m *MockAudienceStore) AssignAudienceToUser(ctx context0.Context, userUUID, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignAudienceToUser", ctx, userUUID, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignAudienceToUser indicates an expected call of AssignAudienceToUser.
func (mr *MockAudienceStoreMockRecorder) AssignAudienceToUser(ctx, userUUID, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignAudienceToUser", reflect.TypeOf((*MockAudienceStore)(nil).AssignAudienceToUser), ctx, userUUID, audience)
}

// GetAllowedAudiences mocks base method.
func (m *MockAudienceStore) GetAllowedAudiences(ctx context0.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedAudiences", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowedAudiences indicates an expected call of GetAllowedAudiences.
func (mr *MockAudienceStoreMockRecorder) GetAllowedAudiences(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedAudiences", reflect.TypeOf((*MockAudienceStore)(nil).GetAllowedAudiences), ctx)
}

// GetUserAudiences mocks base method.
func (m *MockAudienceStore) GetUserAudiences(ctx context0.Context, userUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAudiences", ctx, userUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAudiences indicates an expected call of GetUserAudiences.
func (mr *MockAudienceStoreMockRecorder) GetUserAudiences(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAudiences", reflect.TypeOf((*MockAudienceStore)(nil).GetUserAudiences), ctx, userUUID)
}

// IsValidAudience mocks base method.
func (m *MockAudienceStore) IsValidAudience(ctx context0.Context, audience string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidAudience", ctx, audience)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidAudience indicates an expected call of IsValidAudience.
func (mr *MockAudienceStoreMockRecorder) IsValidAudience(ctx, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidAudience", reflect.TypeOf((*MockAudienceStore)(nil).IsValidAudience), ctx, audience)
}

// RegisterAudience mocks base method.
func (m *MockAudienceStore) RegisterAudience(ctx context0.Context, audience string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAudience", ctx, audience, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAudience indicates an expected call of RegisterAudience.
func (mr *MockAudienceStoreMockRecorder) RegisterAudience(ctx, audience, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAudience", reflect.TypeOf((*MockAudienceStore)(nil).RegisterAudience), ctx, audience, metadata)
}

// RevokeAudience mocks base method.
func (m *MockAudienceStore) RevokeAudience(ctx context0.Context, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAudience", ctx, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAudience indicates an expected call of RevokeAudience.
func (mr *MockAudienceStoreMockRecorder) RevokeAudience(ctx, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAudience", reflect.TypeOf((*MockAudienceStore)(nil).RevokeAudience), ctx, audience)
}

// UnassignAudienceFromUser mocks base method.
func (m *MockAudienceStore) UnassignAudienceFromUser(ctx context0.Context, userUUID, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignAudienceFromUser", ctx, userUUID, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignAudienceFromUser indicates an expected call of UnassignAudienceFromUser.
func (mr *MockAudienceStoreMockRecorder) UnassignAudienceFromUser(ctx, userUUID, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignAudienceFromUser", reflect.TypeOf((*MockAudienceStore)(nil).UnassignAudienceFromUser), ctx, userUUID, audience)
}
