// Code generated by MockGen. DO NOT EDIT.
// Source: usecases_interface.go
//
// Generated by this command:
//
//	mockgen -source=usecases_interface.go -destination=../mocks/mock_usescases.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "MydroX/anicetus/internal/common/context"
	dto "MydroX/anicetus/internal/iam/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIamUsecasesService is a mock of IamUsecasesService interface.
type MockIamUsecasesService struct {
	ctrl     *gomock.Controller
	recorder *MockIamUsecasesServiceMockRecorder
	isgomock struct{}
}

// MockIamUsecasesServiceMockRecorder is the mock recorder for MockIamUsecasesService.
type MockIamUsecasesServiceMockRecorder struct {
	mock *MockIamUsecasesService
}

// NewMockIamUsecasesService creates a new mock instance.
func NewMockIamUsecasesService(ctrl *gomock.Controller) *MockIamUsecasesService {
	mock := &MockIamUsecasesService{ctrl: ctrl}
	mock.recorder = &MockIamUsecasesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIamUsecasesService) EXPECT() *MockIamUsecasesServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockIamUsecasesService) Login(ctx *context.AppContext, req *dto.LoginRequest) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockIamUsecasesServiceMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIamUsecasesService)(nil).Login), ctx, req)
}

// Logout mocks base method.
func (m *MockIamUsecasesService) Logout(ctx *context.AppContext, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockIamUsecasesServiceMockRecorder) Logout(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockIamUsecasesService)(nil).Logout), ctx, token)
}

// RefreshToken mocks base method.
func (m *MockIamUsecasesService) RefreshToken(ctx *context.AppContext, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIamUsecasesServiceMockRecorder) RefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIamUsecasesService)(nil).RefreshToken), ctx, token)
}
