// Code generated by MockGen. DO NOT EDIT.
// Source: repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=repository_interface.go -destination=../mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceStore is a mock of ServiceStore interface.
type MockServiceStore struct {
	ctrl     *gomock.Controller
	recorder *MockServiceStoreMockRecorder
	isgomock struct{}
}

// MockServiceStoreMockRecorder is the mock recorder for MockServiceStore.
type MockServiceStoreMockRecorder struct {
	mock *MockServiceStore
}

// NewMockServiceStore creates a new mock instance.
func NewMockServiceStore(ctrl *gomock.Controller) *MockServiceStore {
	mock := &MockServiceStore{ctrl: ctrl}
	mock.recorder = &MockServiceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceStore) EXPECT() *MockServiceStoreMockRecorder {
	return m.recorder
}

// AssignServiceToUser mocks base method.
func (m *MockServiceStore) AssignServiceToUser(ctx context.Context, userUUID, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignServiceToUser", ctx, userUUID, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignServiceToUser indicates an expected call of AssignServiceToUser.
func (mr *MockServiceStoreMockRecorder) AssignServiceToUser(ctx, userUUID, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignServiceToUser", reflect.TypeOf((*MockServiceStore)(nil).AssignServiceToUser), ctx, userUUID, audience)
}

// GetAllowedServices mocks base method.
func (m *MockServiceStore) GetAllowedServices(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedServices", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowedServices indicates an expected call of GetAllowedServices.
func (mr *MockServiceStoreMockRecorder) GetAllowedServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedServices", reflect.TypeOf((*MockServiceStore)(nil).GetAllowedServices), ctx)
}

// GetUserServices mocks base method.
func (m *MockServiceStore) GetUserServices(ctx context.Context, userUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserServices", ctx, userUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserServices indicates an expected call of GetUserServices.
func (mr *MockServiceStoreMockRecorder) GetUserServices(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserServices", reflect.TypeOf((*MockServiceStore)(nil).GetUserServices), ctx, userUUID)
}

// IsValidService mocks base method.
func (m *MockServiceStore) IsValidService(ctx context.Context, audience string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidService", ctx, audience)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidService indicates an expected call of IsValidService.
func (mr *MockServiceStoreMockRecorder) IsValidService(ctx, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidService", reflect.TypeOf((*MockServiceStore)(nil).IsValidService), ctx, audience)
}

// RegisterService mocks base method.
func (m *MockServiceStore) RegisterService(ctx context.Context, audience string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterService", ctx, audience, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterService indicates an expected call of RegisterService.
func (mr *MockServiceStoreMockRecorder) RegisterService(ctx, audience, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterService", reflect.TypeOf((*MockServiceStore)(nil).RegisterService), ctx, audience, metadata)
}

// RevokeService mocks base method.
func (m *MockServiceStore) RevokeService(ctx context.Context, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeService", ctx, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeService indicates an expected call of RevokeService.
func (mr *MockServiceStoreMockRecorder) RevokeService(ctx, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeService", reflect.TypeOf((*MockServiceStore)(nil).RevokeService), ctx, audience)
}

// UnassignServiceFromUser mocks base method.
func (m *MockServiceStore) UnassignServiceFromUser(ctx context.Context, userUUID, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignServiceFromUser", ctx, userUUID, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignServiceFromUser indicates an expected call of UnassignServiceFromUser.
func (mr *MockServiceStoreMockRecorder) UnassignServiceFromUser(ctx, userUUID, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignServiceFromUser", reflect.TypeOf((*MockServiceStore)(nil).UnassignServiceFromUser), ctx, userUUID, audience)
}
