// Code generated by MockGen. DO NOT EDIT.
// Source: usecases_interface.go
//
// Generated by this command:
//
//	mockgen -source=usecases_interface.go -destination=../mocks/mock_usecases.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "MydroX/anicetus/internal/services/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServicesUsecases is a mock of ServicesUsecases interface.
type MockServicesUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockServicesUsecasesMockRecorder
	isgomock struct{}
}

// MockServicesUsecasesMockRecorder is the mock recorder for MockServicesUsecases.
type MockServicesUsecasesMockRecorder struct {
	mock *MockServicesUsecases
}

// NewMockServicesUsecases creates a new mock instance.
func NewMockServicesUsecases(ctrl *gomock.Controller) *MockServicesUsecases {
	mock := &MockServicesUsecases{ctrl: ctrl}
	mock.recorder = &MockServicesUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicesUsecases) EXPECT() *MockServicesUsecasesMockRecorder {
	return m.recorder
}

// AssignServiceToUser mocks base method.
func (m *MockServicesUsecases) AssignServiceToUser(ctx context.Context, userUUID string, req *dto.AssignServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignServiceToUser", ctx, userUUID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignServiceToUser indicates an expected call of AssignServiceToUser.
func (mr *MockServicesUsecasesMockRecorder) AssignServiceToUser(ctx, userUUID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignServiceToUser", reflect.TypeOf((*MockServicesUsecases)(nil).AssignServiceToUser), ctx, userUUID, req)
}

// GetAllServices mocks base method.
func (m *MockServicesUsecases) GetAllServices(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllServices", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllServices indicates an expected call of GetAllServices.
func (mr *MockServicesUsecasesMockRecorder) GetAllServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllServices", reflect.TypeOf((*MockServicesUsecases)(nil).GetAllServices), ctx)
}

// GetUserServices mocks base method.
func (m *MockServicesUsecases) GetUserServices(ctx context.Context, userUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserServices", ctx, userUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserServices indicates an expected call of GetUserServices.
func (mr *MockServicesUsecasesMockRecorder) GetUserServices(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserServices", reflect.TypeOf((*MockServicesUsecases)(nil).GetUserServices), ctx, userUUID)
}

// RegisterService mocks base method.
func (m *MockServicesUsecases) RegisterService(ctx context.Context, req *dto.RegisterServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterService", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterService indicates an expected call of RegisterService.
func (mr *MockServicesUsecasesMockRecorder) RegisterService(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterService", reflect.TypeOf((*MockServicesUsecases)(nil).RegisterService), ctx, req)
}

// RevokeService mocks base method.
func (m *MockServicesUsecases) RevokeService(ctx context.Context, audience string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeService", ctx, audience)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeService indicates an expected call of RevokeService.
func (mr *MockServicesUsecasesMockRecorder) RevokeService(ctx, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeService", reflect.TypeOf((*MockServicesUsecases)(nil).RevokeService), ctx, audience)
}
